# Meta Data for SEO

## Homepage
title = "Hall of Meat"
titleSeparator = ""
titleAddition = ""
description = "Custom servers for the Skate games"

# ## Open Graph
# images = ["hallofmeat.png"]
# ogLocale = "en_US"
# domainTLD = "hallofmeat.net"
# titleHome = "Hall of Meat"

# ## Twitter Cards
# twitterSite = ""
# twitterCreator = ""

# ## JSON-LD
# # schemaType = "Person"
# schemaType = "Organization"
# schemaName = "Hall of Meat"
# schemaAuthor = ""
# schemaAuthorTwitter = ""
# schemaAuthorLinkedIn = ""
# schemaAuthorGitHub = ""
# schemaLocale = "en-US"
# schemaLogo = "hallofmeat.png"
# schemaLogoWidth = 512
# schemaLogoHeight = 512
# schemaImage = "hallofmeat.png"
# schemaImageWidth = 1280
# schemaImageHeight = 640
# schemaTwitter = ""
# schemaLinkedIn = ""
# schemaGitHub = ""
# schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#d00000"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Powered by <a href=\"https://gohugo.io/\">Hugo</a> and <a href=\"https://getdoks.org/\">Doks</a>"
copyRight = ""

# Alert
alert = false
alertText = ""

# Edit Page
docsRepo = "https://github.com/hallofmeat/hallofmeat.github.io"
editPage = false

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = false
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  collapsibleSidebar = false
